owner: Danjoe4
repo: upptime 
domain: daniel-broderick.com

sites:
  - name: Server Resources Monitor
    url: https://glances.daniel-broderick.com
  - name: Bioinformatics file converter
    url: https://bioconvert.daniel-broderick.com
  - name: Vault Application Pitch Page
    url: https://vaultqr-app.daniel-broderick.com
  - name: Vault QR Code Generator
    url: https://vaultqr-generate.daniel-broderick.com
  - name: Coder Remote Dev Environments
    url: https://coder.daniel-broderick.com
  - name: Torrent Streaming Server
    url: https://torrent-stream.daniel-broderick.com
  - name: Minecraft Server
    url: minecraft.daniel-broderick.com
    port: 25565 # routed via https://tcpshield.com/
    check: "tcp-ping"

status-website:
  cname: daniel-broderick.com
  logoUrl: https://raw.githubusercontent.com/Danjoe4/upptime/master/assets/android-chrome-512x512.png
  favicon: https://raw.githubusercontent.com/Danjoe4/upptime/master/assets/favicon-32x32.png
  name: Daniel Broderick
  introTitle: "Welcome to my website."
  introMessage: >
    Instead of a generic resume site which would only serve to replicate [my LinkedIn](https://www.linkedin.com/in/d-brod/), 
    this site is dedicated to tracking all my services, servers, and projects. Most of which are self hosted on [this machine](https://www.lenovo.com/us/en/p/desktops/thinkcentre/m-series-tiny/thinkcentre-m720q/11tc1mtm72q).
    Feel free to take a look around. Send an email to [roles@daniel-broderick.com](mailto:roles@daniel-broderick.com) 
    if you'd like to offer me a job; open to full-time, contract, or freelance opportunities.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
  
  # yes I tried to do this with yaml variables but it was too much of a pain
  customHeadHtml: >
    <script> 
    const urlMapping = {
      "https://daniel-broderick.com/history/server-resources-monitor": "https://glances.daniel-broderick.com/",
      "https://daniel-broderick.com/history/bioinformatics-file-converter": "https://bioconvert.daniel-broderick.com/",
      "https://daniel-broderick.com/history/vault-application-pitch-page": "https://vaultqr-app.daniel-broderick.com",
      "https://daniel-broderick.com/history/vault-qr-code-generator": "https://vaultqr-generate.daniel-broderick.com",
      "https://daniel-broderick.com/history/coder-remote-dev-environments": "https://coder.daniel-broderick.com",
      "https://daniel-broderick.com/history/torrent-streaming-server": "https://torrent-stream.daniel-broderick.com"
    };

    document.addEventListener("load", function(){
      const anchors = document.querySelectorAll('a');
      const matchingHrefs = [];
      anchors.forEach(anchor => {
          const href = anchor.getAttribute('href');
          if (href && urlMapping[href]) {
            anchor.setAttribute('href', urlMapping[href]);
          }
      });
    });
    </script>